# -*- coding: utf-8 -*-
"""Data Cleaning Census+Merge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yc6iDPBh-E9ncZTwOCqGDL7zn6WWrnM-
"""

import requests
import pandas as pd

# I will use the 2022 ACS 5-year dataset because it is stable and widely used
YEAR = 2022
BASE_URL = f"https://api.census.gov/data/{YEAR}/acs/acs5"

# Pull median income and total population for all ZIP Code Tabulation Areas
params = {
    "get": "B19013_001E,B01003_001E",
    "for": "zip code tabulation area:*"
}

response = requests.get(BASE_URL, params=params)
response.raise_for_status()

# Convert the JSON response into a pandas DataFrame
data = response.json()
census_df = pd.DataFrame(data[1:], columns=data[0])

# Take a quick look
census_df.head()

# Rename columns to something easier to work with
census_df = census_df.rename(columns={
    "zip code tabulation area": "zip",
    "B19013_001E": "median_income",
    "B01003_001E": "population"
})

# Convert income and population columns to numeric values
# If something cannot be converted, set it as NaN
census_df["median_income"] = pd.to_numeric(census_df["median_income"], errors="coerce")
census_df["population"] = pd.to_numeric(census_df["population"], errors="coerce")

# Make sure ZIP codes are stored as 5-digit strings
census_df["zip"] = census_df["zip"].astype(str).str.zfill(5)

# Keep only the columns required for this project
census_df = census_df[["zip", "median_income", "population"]]

# Drop rows with missing income or population values
census_df = census_df.dropna(subset=["median_income", "population"])

# Double-check that all ZIP codes have length 5
census_df["zip"].map(len).value_counts()

import pandas as pd

zillow_df = pd.read_csv("Zip_zori_uc_sfrcondomfr_sm_month.csv")

# See what columns exist
zillow_df.columns.tolist()

# Define the three cities we care about
target_cities = ["San Francisco", "Los Angeles", "San Diego"]

# Filter Zillow ZIP-level data for those cities
selected_zips = (
    zillow_df.loc[zillow_df["City"].isin(target_cities), "RegionName"]
    .astype(str)
    .str.zfill(5)
    .unique()
)

# Check how many ZIP codes we extracted
len(selected_zips)

# Filter census data to keep only the selected ZIP codes
filtered_df = census_df[census_df["zip"].isin(selected_zips)].copy()

# Check the result size
filtered_df.shape

# Save the cleaned ZIP-level dataset for the project
filtered_df.to_csv("census_zip_income_population.csv", index=False)

len(selected_zips)

# Make sure all selected ZIPs are from California
zillow_df.loc[
    zillow_df["RegionName"].astype(str).str.zfill(5).isin(selected_zips),
    "StateName"
].unique()

# Identify date columns
date_cols = [c for c in zillow_df.columns if "-" in c and c[0:4].isdigit()]

# Quick sanity check
date_cols[:5], date_cols[-5:], len(date_cols)

# Pick date columns for each year
cols_2024 = [c for c in date_cols if c.startswith("2024-")]
cols_2025 = [c for c in date_cols if c.startswith("2025-")]

len(cols_2024), len(cols_2025), cols_2024[:3], cols_2025[:3]

# Build a ZIP-level rent summary table
zillow_zip = zillow_df[zillow_df["RegionName"].astype(str).str.zfill(5).isin(selected_zips)].copy()

# Standardize ZIP as a 5-digit string
zillow_zip["zip"] = zillow_zip["RegionName"].astype(str).str.zfill(5)

# Compute yearly average rent (not time series, just a summary number)
zillow_zip["avg_rent_2024"] = zillow_zip[cols_2024].mean(axis=1, skipna=True)
zillow_zip["avg_rent_2025"] = zillow_zip[cols_2025].mean(axis=1, skipna=True)

# Keep only what we need for merging
zillow_rent_df = zillow_zip[["zip", "avg_rent_2024", "avg_rent_2025"]].copy()

zillow_rent_df.head()

# Missing values are expected for 2025 if Zillow doesn't have all months yet
zillow_rent_df.isna().mean()

# Merge Census (income/population) with Zillow rent by ZIP
merged_zip_df = filtered_df.merge(zillow_rent_df, on="zip", how="left")

merged_zip_df.shape, merged_zip_df.head()

# Sanity check: how many ZIPs didn't match Zillow rent
merged_zip_df["avg_rent_2024"].isna().mean(), merged_zip_df["avg_rent_2025"].isna().mean()

# List a few ZIPs with missing rent so we know what’s going on
merged_zip_df.loc[
    merged_zip_df["avg_rent_2024"].isna() | merged_zip_df["avg_rent_2025"].isna(),
    ["zip", "median_income", "population", "avg_rent_2024", "avg_rent_2025"]
].head(10)

# Keep the final output clean and consistent for the team
merged_zip_df = merged_zip_df.sort_values("zip").reset_index(drop=True)

# Export the merged dataset (this is what I hand off to the group)
merged_zip_df.to_csv("zip_census_zillow_merged.csv", index=False)

airbnb_zillow = pd.read_csv("airbnb_zillow.csv")
census_df = pd.read_csv("zip_census_zillow_merged.csv")


airbnb_zillow["zip"] = airbnb_zillow["zip"].astype(str).str.zfill(5)
census_df["zip"] = census_df["zip"].astype(str).str.zfill(5)

final_df = airbnb_zillow.merge(
    census_df[["zip", "median_income", "population"]],
    on="zip",
    how="left"
)

final_df.to_csv("final_merged_dataset.csv", index=False)
