# -*- coding: utf-8 -*-
"""Visualization partIII.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ChttGBWsJuZTcBnEz_pR8yPXJSE4mDZH
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# read the final merged dataset
# this file already contains the variables we need
df = pd.read_csv("data/processed data/final.csv")

# keep only the columns we need for section III
df3 = df[["city", "zip", "airbnb_count", "avg_rent_2024"]].copy()

# make sure these two columns are numeric
# sometimes csv reading can treat them as strings
df3["airbnb_count"] = pd.to_numeric(df3["airbnb_count"], errors="coerce")
df3["avg_rent_2024"] = pd.to_numeric(df3["avg_rent_2024"], errors="coerce")

# drop rows where either variable is missing
# we need both values for plotting
df3 = df3.dropna(subset=["airbnb_count", "avg_rent_2024"])


# idea: check if areas with more Airbnb listings tend to have higher rent

plt.figure(figsize=(8,6))

# define colors for each city
colors = {
    "Los Angeles": "tab:blue",
    "San Diego": "tab:orange",
    "San Francisco": "tab:green"
}

# plot each city separately so colors are different
for city in df3["city"].unique():

    city_data = df3[df3["city"] == city]

    plt.scatter(
        city_data["airbnb_count"],
        city_data["avg_rent_2024"],
        color=colors.get(city, "gray"),
        label=city,
        alpha=0.6,
        s=35
    )

plt.xlabel("Airbnb Count")
plt.ylabel("Average Rent 2024")
plt.title("Airbnb Count vs Average Rent")

# zoom in to show the main cluster of points
plt.xlim(0, 800)
plt.ylim(1800, 4500)

plt.legend()

plt.grid(alpha=0.3)
plt.tight_layout()

plt.savefig("figure1_scatter_airbnb_vs_rent.png", dpi=300)

plt.show()


# idea: split Airbnb count into three groups
# then compare rent distribution across groups

df3["airbnb_level"] = pd.qcut(
    df3["airbnb_count"],
    q=3,
    labels=["Low", "Medium", "High"]
)

low = df3[df3["airbnb_level"] == "Low"]["avg_rent_2024"]
med = df3[df3["airbnb_level"] == "Medium"]["avg_rent_2024"]
high = df3[df3["airbnb_level"] == "High"]["avg_rent_2024"]

plt.figure(figsize=(8, 6))

plt.boxplot(
    [low, med, high],
    tick_labels=["Low Airbnb", "Medium Airbnb", "High Airbnb"],
    widths=0.45
)

plt.xlabel("Airbnb Count Group")
plt.ylabel("Average Rent 2024")
plt.title("Rent Distribution by Airbnb Activity")

# most values are in this range
# so this makes the boxes easier to compare
plt.ylim(1800, 4500)

plt.grid(alpha=0.3)
plt.tight_layout()

plt.savefig("figure2_rent_boxplot.png", dpi=300)

plt.show()


# idea: compare average Airbnb activity and rent across cities
# the two variables are on very different scales
# so I split them into two panels to make the figure easier to read

city_summary = (
    df3
    .groupby("city")
    .agg({
        "airbnb_count": "mean",
        "avg_rent_2024": "mean"
    })
    .reset_index()
)

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

axes[0].bar(city_summary["city"], city_summary["airbnb_count"])
axes[0].set_title("Average Airbnb Count by City")
axes[0].set_xlabel("City")
axes[0].set_ylabel("Average Airbnb Count")
axes[0].tick_params(axis="x", rotation=45)
axes[0].grid(axis="y", alpha=0.3)

axes[1].bar(city_summary["city"], city_summary["avg_rent_2024"])
axes[1].set_title("Average Rent 2024 by City")
axes[1].set_xlabel("City")
axes[1].set_ylabel("Average Rent 2024")
axes[1].tick_params(axis="x", rotation=45)
axes[1].grid(axis="y", alpha=0.3)

plt.tight_layout()

plt.savefig("figure3_city_comparison.png", dpi=300)

plt.show()

