# -*- coding: utf-8 -*-
"""Visualization spatial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OYhi89zWUDEBY0X9WeHxY7Vem70xKZbA
"""

import pandas as pd
import geopandas as gpd
from pathlib import Path

final=pd.read_csv("data/processed data/final.csv")

final.head()

import geopandas as gpd

zip_map = gpd.read_file(
"tl_2020_us_zcta520.shp"
)

zip_map.columns

zip_map_ca = zip_map[
    zip_map["ZCTA5CE20"].str.startswith(("90","91","92","93","94","95"))
]

final["zip"] = final["zip"].astype(str)
map_data = zip_map_ca.merge(
    final,
    left_on="ZCTA5CE20",
    right_on="zip",
    how="inner"
)

airbnb_density = final.groupby("zip").size().reset_index(name="airbnb_density")

zip_level = map_data.merge(
    airbnb_density,
    on="zip",
    how="left"
)

zip_level["airbnb_density"].describe()

zip_level.head()

zip_level['airbnb_count'].describe()

del zip_level["airbnb_density"]

"""#Airbnb density map vs. Rent choropleth"""

import matplotlib.pyplot as plt
la_df = map_data[map_data["city"] == "Los Angeles"]

fig, axes = plt.subplots(1, 2, figsize=(14,7))

# Airbnb map
la_df.plot(
    column="airbnb_count",
    cmap="YlOrRd",
    legend=True,
    edgecolor="black",
    linewidth=0.4,
    legend_kwds={"label": "Airbnb Listing Density"},
    ax=axes[0]
)

axes[0].set_title("Airbnb Density – Los Angeles")
axes[0].axis("off")


# Rent map
la_df.plot(
    column="avg_rent_2024",
    cmap="Blues",
    legend=True,
    edgecolor="black",
    linewidth=0.4,
    legend_kwds={"label": "Average Rent (USD)"},
    missing_kwds={"color":"lightgrey"},
    ax=axes[1]
)

axes[1].set_title("Average Rent – Los Angeles")
axes[1].axis("off")

plt.tight_layout()
plt.show()

la_df.loc[la_df["airbnb_count"].idxmax()]

la_df.loc[la_df["avg_rent_2024"].idxmax()]

la_df[["zip","airbnb_count"]].sort_values(
    by="airbnb_count",
    ascending=False
).head(5)

la_df[["zip","avg_rent_2024"]].sort_values(
    by="avg_rent_2024",
    ascending=False
).head(5)

import matplotlib.pyplot as plt
sf_df = map_data[map_data["city"] == "San Francisco"]

fig, axes = plt.subplots(1, 2, figsize=(14,7))

# Airbnb map
sf_df.plot(
    column="airbnb_count",
    cmap="YlOrRd",
    legend=True,
    edgecolor="black",
    linewidth=0.4,
    legend_kwds={"label": "Airbnb Listing Density"},
    ax=axes[0]
)

axes[0].set_title("Airbnb Density – San Francisco")
axes[0].axis("off")


# Rent map
sf_df.plot(
    column="avg_rent_2024",
    cmap="Blues",
    legend=True,
    edgecolor="black",
    linewidth=0.4,
    legend_kwds={"label": "Average Rent (USD)"},
    missing_kwds={"color":"lightgrey"},
    ax=axes[1]
)

axes[1].set_title("Average Rent – San Francisco")
axes[1].axis("off")

plt.tight_layout()
plt.show()

sf_df.loc[sf_df["airbnb_count"].idxmax()]

sf_df.loc[sf_df["avg_rent_2024"].idxmax()]

sf_df[["zip","airbnb_count"]].sort_values(
    by="airbnb_count",
    ascending=False
).head(5)

sf_df[["zip","avg_rent_2024"]].sort_values(
    by="avg_rent_2024",
    ascending=False
).head(5)

import matplotlib.pyplot as plt
sd_df = map_data[map_data["city"] == "San Diego"]

fig, axes = plt.subplots(1, 2, figsize=(14,7))

# Airbnb map
sd_df.plot(
    column="airbnb_count",
    cmap="YlOrRd",
    legend=True,
    edgecolor="black",
    linewidth=0.4,
    legend_kwds={"label": "Airbnb Listing Density"},
    ax=axes[0]
)

axes[0].set_title("Airbnb Density – San Diego")
axes[0].axis("off")


# Rent map
sd_df.plot(
    column="avg_rent_2024",
    cmap="Blues",
    legend=True,
    edgecolor="black",
    linewidth=0.4,
    legend_kwds={"label": "Average Rent (USD)"},
    missing_kwds={"color":"lightgrey"},
    ax=axes[1]
)

axes[1].set_title("Average Rent – San Diego")
axes[1].axis("off")

plt.tight_layout()
plt.show()

import geopandas as gpd
import folium
from folium.plugins import DualMap, Search
import branca.colormap as cm

gdf = gdf.to_crs("EPSG:4326")

dens_col = "airbnb_count"
rent_col = "avg_rent_2024"

dens_cmap = cm.linear.YlOrRd_09.scale(gdf[dens_col].min(), gdf[dens_col].max())
rent_cmap = cm.linear.Blues_09.scale(gdf[rent_col].min(), gdf[rent_col].max())

m = DualMap(
    location=[gdf.geometry.centroid.y.mean(), gdf.geometry.centroid.x.mean()],
    zoom_start=10,
    tiles="cartodbpositron"
)

airbnb_layer = folium.GeoJson(
    gdf,
    name="Airbnb density",
    style_function=lambda feat: {
        "fillColor": dens_cmap(feat["properties"][dens_col]) if feat["properties"][dens_col] else "#cccccc",
        "color": "black",
        "weight": 0.4,
        "fillOpacity": 0.75,
    },
    tooltip=folium.GeoJsonTooltip(
        fields=["zip", dens_col],
        aliases=["ZIP", "Airbnb density"],
    ),
)

airbnb_layer.add_to(m.m1)

dens_cmap.caption = "Airbnb Listing Density"
dens_cmap.add_to(m.m1)

rent_layer = folium.GeoJson(
    gdf,
    name="Average rent",
    style_function=lambda feat: {
        "fillColor": rent_cmap(feat["properties"][rent_col]) if feat["properties"][rent_col] else "#cccccc",
        "color": "black",
        "weight": 0.4,
        "fillOpacity": 0.75,
    },
    tooltip=folium.GeoJsonTooltip(
        fields=["zip", rent_col],
        aliases=["ZIP", "Avg Rent"],
    ),
)

rent_layer.add_to(m.m2)

rent_cmap.caption = "Average Rent (USD)"
rent_cmap.add_to(m.m2)

Search(
    layer=airbnb_layer,
    search_label="zip",
    placeholder="Search ZIP code",
    collapsed=False,
).add_to(m.m1)

Search(
    layer=rent_layer,
    search_label="zip",
    placeholder="Search ZIP code",
    collapsed=False,
).add_to(m.m2)

m.save("try_interactive_map.html")

sd_df.loc[sd_df["airbnb_count"].idxmax()]

sd_df.loc[sd_df["avg_rent_2024"].idxmax()]

sd_df[["zip","airbnb_count"]].sort_values(
    by="airbnb_count",
    ascending=False
).head(5)

sd_df[["zip","avg_rent_2024"]].sort_values(
    by="avg_rent_2024",
    ascending=False
).head(5)