# -*- coding: utf-8 -*-
"""Visualization_pt_v.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AafRMTYDB6zgc43BF4Q-Z5Sk7V3GHMRA

We are investigating how AirBnB density and activity influence long term rental conditions and neighborhood characteristics of the following cities: Los Angeles, San Francisco, and San Diego.

The goal of this portion of the project is to provide city-level aggregates for the following variables:
    - Average AirBnB price
    - Average rent from 2024
    - AirBnB density (count)
"""

# Importing necessary packages and datasets


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


data = pd.read_csv("data/processed data/final.csv")
data = data.dropna() #remove NaN/NA values
#print(data)

# This code calculates the average AirBnB density per zip code for each of the three cities.
data_for_averages = data[['city', 'avg_rent_2024', 'avg_airbnb_price', 'airbnb_count']].copy()
#print(data_for_averages)

averages = data_for_averages.groupby('city').mean()
print(averages)


# This code obtains the number of zip codes included in each of the cities
zips_per_city = data_for_averages.groupby('city').count()
#print(zips_per_city)

"""The following are the number of area (ZIP) codes included in each city:
    - Los Angeles: 216
    - San Diego: 39
    - San Francisco: 19
"""

# This code creates a grouped barplot for average rent (2024), AirBnB price, and AirBnB density per city.
plt.style.use('_mpl-gallery')
summary_x = ['Average Rent (2024)', "Average AirBnB price/night", "AirBnB Count (Density)"]
summary_y = {
    'Los Angeles (216 ZIP codes)': (2890.472997 , 255.561760, 156.689815),
    'San Diego (39 ZIP codes)': (2891.361488, 517.663829, 288.051282),
    'San Francisco (19 ZIP codes)': (3208.393892, 362.423896 , 277.157895),
}

x = np.arange(len(summary_x))  # label locations
width = 0.25  # the width of the bars
multiplier = 0

fig, ax = plt.subplots(figsize=(10, 8))

for attribute, measurement in summary_y.items():
    offset = width * multiplier
    rects = ax.bar(x + offset, measurement, width, label=attribute)
    ax.bar_label(rects, padding=3)
    multiplier += 1

# This code adds important labels to the graph.
ax.set_ylabel('Cost (in USD)')
ax.set_title('Summary Values by City')
ax.set_xticks(x + width, summary_x)
ax.legend(loc='upper right', ncols=3, fontsize=9)

plt.savefig('summary.png', bbox_inches='tight')

"""The next task is to create scatterplots for each city comparing the AirBnB price to the average rent of each city in 2024. The AirBnB count (density) is located next to the city names in the title.

These scatterplots indicate that there may be a positive relationship between AirBnB price and average rent price in Los Angeles and San Francisco, whereas the price of rent in San Diego might be driven by other factors besides AirBnB price.
"""

# This code generates the scatterplot comparing the AirBnB price to the average rent in the city of Los Angeles.
la_data = data[data['city'] == 'Los Angeles']
#print(la_data)

plt.figure(figsize=(5,4))

x = la_data['avg_airbnb_price']
y = la_data['avg_rent_2024']

plt.scatter(x, y, c='red')
plt.title("LOS ANGELES (across 216 ZIP Codes)")
plt.xlabel("Average AirBnB Price/night (in USD)")
plt.ylabel("Average Rent (2024) in USD")

plt.savefig('la.png', bbox_inches='tight')

# This code generates the scatterplot comparing the AirBnB price per night to the average rent in the city of San Diego.
sd_data = data[data['city'] == 'San Diego']

plt.figure(figsize=(5,4))

x = sd_data['avg_airbnb_price']
y = sd_data['avg_rent_2024']

plt.scatter(x, y, c='blue')
plt.title("SAN DIEGO (across 39 ZIP Codes)")
plt.xlabel("Average AirBnB Price (in USD)")
plt.ylabel("Average Rent (2024) in USD")

plt.savefig('sd.png', bbox_inches='tight')

# This code generates the scatterplot comparing the AirBnB price to the average rent in the city of San Francisco.
sf_data = data[data['city'] == 'San Francisco']

plt.figure(figsize=(5,4))

x = sf_data['avg_airbnb_price']
y = sf_data['avg_rent_2024']

plt.scatter(x, y, c='purple')
plt.title("SAN FRANCISCO (across 19 ZIP Codes)")
plt.xlabel("Average AirBnB Price/night (in USD)")
plt.ylabel("Average Rent (2024) in USD")

plt.savefig('sf.png', bbox_inches='tight')