# -*- coding: utf-8 -*-
"""DataCleaning InsideAirbnb+Merge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1No0go4x-xknPOdZy1OMB8CVfF7Ez2f9f
"""

# pip install geopandas pyogrio shapely

import pandas as pd
import geopandas as gpd
from pathlib import Path

listings = pd.read_csv("data/processed_data/listings.csv")

zips = gpd.read_file(
    "data/spatial/tl_2020_us_zcta520.shp"
)

print(zips.shape)
print(zips.columns)
print(zips.head())

listings_gdf = gpd.GeoDataFrame(
    listings.copy(),
    geometry=gpd.points_from_xy(listings["longitude"], listings["latitude"]),
    crs="EPSG:4326"
)

zips = zips.to_crs("EPSG:4326")

joined = gpd.sjoin(
    listings_gdf,
    zips[["ZCTA5CE20", "geometry"]],
    how="left",
    predicate="within"
).rename(columns={"ZCTA5CE20": "zip"})

joined["zip"] = (
    joined["zip"]
    .astype("string")
    .str.extract(r"(\d+)", expand=False)
    .str.zfill(5)
)

mapped = joined.dropna(subset=["zip"]).drop(columns=["index_right", "geometry"])

print("original rows:", len(listings))
print("mapped rows   :", len(mapped))
print(mapped[["city", "zip"]].head())

print(mapped.columns)

import pandas as pd
#Convert price column into numeric type
mapped["price"] = (
    mapped["price"]
    .astype("string")
    .str.replace(r"[\$,]", "", regex=True)
)

mapped["price"] = pd.to_numeric(mapped["price"], errors="coerce")

mapped["review_score"] = pd.to_numeric(mapped["review_score"], errors="coerce")
mapped["accommodates"] = pd.to_numeric(mapped["accommodates"], errors="coerce")
mapped["is_entire_home"] = pd.to_numeric(mapped["is_entire_home"], errors="coerce")

zip_level = (
    mapped
    .groupby(["city", "zip"], as_index=False)
    .agg(
        airbnb_count=("zip", "size"),
        avg_airbnb_price=("price", "mean"),
        entire_home_ratio=("is_entire_home", "mean"),
        avg_review_score=("review_score", "mean"),
        avg_accommodates=("accommodates", "mean"),
    )
)

print(zip_level.shape)
print(zip_level[["city", "zip"]].duplicated().any())
print(zip_level.head(40000))

zip_level["zip"] = zip_level["zip"].astype(str).str.zfill(5)
zillow["zip"] = zillow["zip"].astype(str).str.zfill(5)

zillow_full=pd.read_csv("/content/drive/Shared drives/STA141b airbnb project/Original datasets/Zillow_updated.csv")

print([c for c in zillow_full.columns if "2024" in c])
print([c for c in zillow_full.columns if "2025" in c])

print(zillow_full.shape)
print(zillow_full.head())

zillow_full = zillow_full.rename(columns={"RegionName": "zip"})
zillow_full["zip"] = zillow_full["zip"].astype(str).str.zfill(5)

cols_2024 = [c for c in zillow_full.columns if "2024" in c]
cols_2025 = [c for c in zillow_full.columns if "2025" in c]

zillow_full["avg_rent_2024"] = zillow_full[cols_2024].mean(axis=1)
zillow_full["avg_rent_2025"] = zillow_full[cols_2025].mean(axis=1)
zillow_full["rent_growth"] = (
    zillow_full["avg_rent_2025"] - zillow_full["avg_rent_2024"]
) / zillow_full["avg_rent_2024"]

zillow_full.head(100)

airbnb_zillow = zip_level.merge(
    zillow_full[["zip", "avg_rent_2024","avg_rent_2025","rent_growth"]],
    on="zip",
    how="inner"
)

print(len(airbnb_zillow))

airbnb_zillow.shape
airbnb_zillow.describe()

airbnb_zillow_clean = airbnb_zillow.dropna(
    subset=["avg_rent_2024", "avg_rent_2025", "rent_growth"]
).copy()

print(len(airbnb_zillow_clean))
del airbnb_zillow_clean

